# Generated by Django 5.0.14 on 2025-07-02 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_avaliacao_estacionamento_alter_avaliacao_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='utiliza veículo'),
        ),
        migrations.CreateModel(
            name='HistoricoOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_ocupadas', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app.estacionamento')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
