# Generated by Django 5.0.14 on 2025-07-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_vehicle_type_historicoocupacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada de latitude para o mapa (ex: -22.9068).', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada de longitude para o mapa (ex: -43.1729).', null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='preco_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço por Hora'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas_disponiveis',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas Disponíveis'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas_totais',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas Totais'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='disponibilidade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', help_text='Calculado automaticamente se as vagas forem preenchidas.', max_length=5, verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nome',
            field=models.CharField(help_text='Nome comercial do estacionamento.', max_length=200, verbose_name='Nome'),
        ),
    ]
