# Generated by Django 5.0.14 on 2025-07-08 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estacionamento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=50, null=True, verbose_name='utiliza veículo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lugar_mora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bairro', verbose_name='Bairro onde mora'),
        ),
    ]
